### ISSUE TITLE
Test Matines Polymorphic factory

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#1326]

**Comment by Barsnes** [comment]
I tested Mantines factory to create a polymorphic component, but it was hard to implement since their functions and types had a deep connection with their other core function and providers.
I also took a look at Charka and MUIs same "factory" functions and types, but came to the same conclusion.

I also had a look at trying to update our `OverridableComponent`, and came close, but in the end it grew too complex and still did not have 100% of the correct types.

We have decided to use `Slot` from radix, and will be updating our components to support this.
