### ISSUE TITLE
`Combobox`: Option to disable keyboard/search in possible values

### ISSUE THREAD

**Issue by olemartinorg** [digdir/designsystemet#1713]
### Description

As per the linked issue, on mobile the keyboard pops up whenever you tap on a `Combobox`. That makes sense when you want to nudge the user to search instead of scroll, but it's annoying when you have 1-3 options to choose from and it's easier to just tap on the option you need instead of typing out that option on a keyboard and _then_ tapping it.

### Additional Information

- https://github.com/Altinn/app-frontend-react/issues/1431

**Comment by Febakke** [comment]
Our combobox is an `input` and I think we should be careful about changing the expected behavior. In this case I would concider using another component for your language selector. 

1. Best and often used solution is to use a [dropdown](https://storybook.designsystemet.no/?path=/docs/komponenter-dropdownmenu--docs) and let the user choose witch element is active in the list. Are there any blockers I might not now about to get toggling elements in the dropdown @Barsnes? 

I would also move it into the header to follow the same pattern as many other pages do. https://github.com/Altinn/app-frontend-react/issues/1859

Example from Altinn.no and SKD 
<img width="510" alt="Skjermbilde 2024-03-20 kl  12 34 16" src="https://github.com/digdir/designsystemet/assets/33222679/b0846900-7f82-4070-b596-ef3936a1f09f">
<img width="245" alt="Skjermbilde 2024-03-20 kl  12 35 23" src="https://github.com/digdir/designsystemet/assets/33222679/aeb688a9-d4a9-4718-9802-847deaff0f17">

2. Use a native select. Much better support on small screens. But you cant style the dropdown, and that will not scale well if you want to add flags or some other elements later. 

3. If we would fix this we would have to recreate the behaviour of the `nativeSelect`. And I think in most cases it would be better to use the native one instead of our custom select if you only need the same functionality as the `nativeSelect`

**Comment by olemartinorg** [comment]
@Febakke Fantastic answer - I agree :100:. I would think there's still a case for regular form-inputs (the `Dropdown` component in Altinn 3 apps) with few options to choose from. I take it we'd have to style a native select (and not use the design system) for such cases, or is there a plan for such a simplified/native-but-slightly-styled select-input for those use-cases?

**Comment by Febakke** [comment]
@olemartinorg 
Sorry, forgot to add a link to our [nativeSelect](https://storybook.designsystemet.no/?path=/docs/komponenter-nativeselect--docs) Its styled like our other inputs, but functions as a native select 😄
