### ISSUE TITLE
Combobox: flushSync was called from inside a lifecycle method

### ISSUE THREAD

**Issue by hansenalexander** [digdir/designsystemet#1730]
### Description of the bug

Not exactly sure what causes this error, but based on the stack trace it looks like it might be related to virtualizing?

![Screenshot from 2024-03-21 13-04-10](https://github.com/digdir/designsystemet/assets/75268558/6825d58c-24ab-4546-9d0f-b296852d852d)

![Screenshot from 2024-03-21 12-46-21](https://github.com/digdir/designsystemet/assets/75268558/ce35a5d1-d774-44bb-abf8-2c1a9ee5cf45)

### Steps To Reproduce

Haven't been able to find a direct pattern, but this seems to cause the error:

1. Add 6+ values in a combobox which has virtual set to true.
2. Close the combobox dropdown.
3. Open the combobox dropdown.

**Comment by Barsnes** [comment]
Thanks for the bug report!
I seem to have found a way to always produce the bug:
- Create a combobox with options, and virtual to `true`
- Open and scroll down a bit
- Close the combobox
- Open and the error should appear

Can you confirm if this always produces the bug as well?

**Comment by hansenalexander** [comment]
> Thanks for the bug report! I seem to have found a way to always produce the bug:
> 
> * Create a combobox with options, and virtual to `true`
> * Open and scroll down a bit
> * Close the combobox
> * Open and the error should appear
> 
> Can you confirm if this always produces the bug as well?

Can confirm, seems to cause the bug every time.

**Comment by Barsnes** [comment]
I have done some testing, and it seems like this issue is happening inside Tanstack Virtual, the library we use for virtualization.
When running their debugger, the warning always occurs after their internal code.
![image](https://github.com/digdir/designsystemet/assets/14057205/41c3d36e-8d26-4c12-99e7-1ace94b17265)

I have noticed that if you scroll back to the top of the scroll container, the bug does not appear. So I will investigate if we can do this before closing the combobox, as a workaround.
