### ISSUE TITLE
Improve the visual appearance of the `Alert` component

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#1790]
The Alert component has been further tested together with our other components, and it turns out that it does not fit in as it is now. Especially the thick frame on the far left and the lack of a frame around which "frames" it properly against different background colors. Title and preamble are not completely connected regarding spacing. Less padding around the alert than there is between title / introduction. We also received feedback that it looked a bit "Windows 95" / old fashioned.

We should design and implement 3 different sizes of the component and and a more suitable design like this:

![Image](https://github.com/digdir/designsystemet/assets/1464915/37334a62-9624-4b52-9c86-07b86e5fb144)

```[tasklist]
### Tasks
- [ ] https://github.com/digdir/designsystemet/issues/1792
- [ ] https://github.com/digdir/designsystemet/issues/1791
```

**Comment by Barsnes** [comment]
When it comes to sizes, we have decided to set a standard font-size **only** for free text inside the alert component.
If you use any of out typography components, the developer has to make sure the correct sizes are being used. Padding will change accordion to the size set.

We will add examples and guidelines for text inside the alert in Storybook.

This is so we can make this component SSR friendly in the future, since we won't need a context.
