### ISSUE TITLE
Redesign radio to match with checkbox

### ISSUE THREAD

**Issue by Febakke** [digdir/designsystemet#2111]
When we implemented radio and checkbox with darkmode. We noticed that they dont match very well. We should try to alter the design of the radio button to handle darkmode better.

**Elements we want**
- checked components are filled
- Contrast color

![Image](https://github.com/digdir/designsystemet/assets/33222679/77581048-a567-454c-aca8-e89b2879fd61)

![Image](https://github.com/digdir/designsystemet/assets/33222679/6d2d9ed1-8fa3-4b5f-833c-70f23aac5696)

```[tasklist]
### Tasks
- [ ] Design new radiobutton component
```

**Comment by Thuneer** [comment]
I think we need to use the contrast color inside the radio button and the checkbox to make sure the contrast is sufficient in both light- and dark mode. Using just the background, as in the second example, is very problematic because a color cannot contrast properly against both dark and light colors at the same time. I like the Mantine example the most. Makes the checkbox and radio buttons fit together very nicely, and also makes sure contrasts work.

**Comment by mrosvik** [comment]
Should use token `accent-contrast-1` to make sure it gets enough contrast. @Febakke

**Comment by Barsnes** [comment]
This has been done in Figma, and in React #2130
