### ISSUE TITLE
Styling bugs with react components in Next branch

### ISSUE THREAD

**Issue by Thuneer** [digdir/designsystemet#2134]
- [x] Radio og checkbox: More spacing between label and description (4px).
- [x] Switch, radio and checkbox: Label 400 font-weight.
- [x] Table `<th>` has 700 font weight, should be 500.
- [x] Divider inside checkbox group not showing. Can see it in "handleliste" here: https://next.theme.designsystemet.no/
- [x] Button inside Table `<th>` for sorting has wrong font size or weight.
- [ ] Wrong spacing below legend and description in a fieldset. Can see it in "handleliste" here: https://next.theme.designsystemet.no/. Gap should be 8px I think.

**Comment by Febakke** [comment]
Both Radio and Checkbox need som tweaking to be correct. 
The gap between legend and radio/check is somewhat to big. It seems like the extra padding around radio/check from the hover state might give us some issues. We need to get it so that the gap is the same as between each input

There is different spacing in the gaps on radios and checkboxes. They should have the same gap.

- [ ] Radio and checkbox should have the same spacing between legend and first input element as between each element. 
- [ ] Radio and checkbox should have the samme spacing 

Something like this:
<img width="541" alt="Skjermbilde 2024-08-12 kl  14 46 14" src="https://github.com/user-attachments/assets/1aa1372e-986c-4ed2-bce8-52e98a8cf5e2">

**The gap for each size**
Large: 20px (spacing-5)
Medium: 16px (spacing-4)
Small: 12px (spacing-3)
