### ISSUE TITLE
Storefront: Bug in safari with frontpage

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#2162]
Can´t see the whole cards

![Image](https://github.com/digdir/designsystemet/assets/1464915/773d6e4b-581b-46a4-9d50-6a93e9bfafe9)

**Comment by Barsnes** [comment]
This is a safari specific bug.
For some reason, when using `overflow: hidden` in Safari, it also hides content still within the padded area of the container.
We should be able to fix this by changing to `overflow-x: hidden`, since that is the axis we want to hide.

In chrome:
![image](https://github.com/digdir/designsystemet/assets/14057205/c21cc93c-e6ab-47a0-9e95-cbb9fa1b8f2d)

**Comment by Barsnes** [comment]
Resolved in #2130
