### ISSUE TITLE
Scroll around Modal vs. only inside

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#2256]
Modal (`<dialog>`) currently only allows scroll inside, but scroll around can be useful. This will also help when having a overflowing element (such as combobox) inside dialog.

![Image](https://github.com/user-attachments/assets/59c3a395-64d3-458a-99ce-3d2fa6b53b52)

**Comment by Barsnes** [comment]
The team discussed this, 19 August 2024:
**We have decided not to have scroll outside because of a few factors:**
- The native dialog element nativley supports scroll inside, and we would need more markup for scroll outside to work.
- Modals should be short an consise, if we only have scroll inside the modal we push consumers to have less content.
- Arrow keys work fine inside the modal, just as they would outside.
- You will never "lose" the close button above the fold, this happens if the user scrolls outside.
- It is a commn pattern on the web to have scroll inside modals.
- It is less likely that the user will miss the scrollbar when using the mouse, and close the modal if the backdrop does it.

Based on these factors we have decided not to support scroll outside, as it pushes good UX practice both for content and functionality.
