### ISSUE TITLE
Update design-tokens & build script to support new border-radius tokens

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#2476]

**Comment by Febakke** [comment]
New Tokens on components

### Small
- Avatar (Square)
- Checkbox
- Tag
### Medium
- Alert
- Accordion
- Dropdown
- Popover
- Text area
### Large
- Card
- Error summary
- Sceleton (rectangle)
- Modal
### Default
- Button
- Combobox
  - Hover on elements inside list has `small`
- Search
- Tooltip
- Textfield
### Full
- Avatar (Circle)
- Badge
- Chip
- Skeleton circle and text

**Comment by unekinn** [comment]
@Febakke some questions:

### Components not mentioned in the comment above

Should these be unchanged?

- Chip with checkbox: large
- Helptext: full
- Radio: hardcoded to 50%
- Switch: full
- Table with border: medium
- Tabs: full

### 
- Shouldn't all form elements have the same radius? Now Combobox had default radius, while Select, Textfield and TextArea have medium
-

**Comment by unekinn** [comment]
Fairly certain "Chip with checkbox" needs to have medium radius for the chip and small radius for the checkbox, so I'm implementing that.

**Comment by Febakke** [comment]
@unekinn 
I updated the comment over here with the components that where missing. But ill have a summary here as well

### Some comments
- Chip with checkbox: I agree, it should have medium border-radius as you pointed out
- Helptext, I believe you are talking about the iconbutton? Yes it should be `full`
- Radio, Im not sure what 50% means, but it should always be a circle and have `full` border radius
- Select should have medium
  - After a discussion with @Thunear we agreed that textfield should not become round as I first wrote. The reason is that it will not look right in form context. (How it aligns with the label) I think all the "form" fields should have `medium` border-radius. Search is a different story and can and often has a circular look. So it should use `default`. 
- Switch, Always full
- Table with border. If there are noe border on the table there is no point in having a border-radius. In Figma this is something you have to set up yourself. But if we need a default value i would use `medium`
- Tabs, there are no border around tabs. Where is this applied? 
- Tag should always keep their square shape. `small`
- Toggle group, Ill write about this further down 👇
- Tooltip can be circular. `full`

### Logic for nicer components
I have seen an issue with components that has elements inside other elements where radius is applied to both. When design components like this you often apply more radius to the outer element. Lets use toggle groups as an example. 

![Skjermbilde 2024-10-15 kl  15 04 31](https://github.com/user-attachments/assets/b535cbdd-89b1-4267-9854-8461d33934df)

Here both `button`and the `togglegroup` border use `8` border-radius. It looks kind of weird. 

![Skjermbilde 2024-10-15 kl  15 06 07](https://github.com/user-attachments/assets/dee95121-d6ae-4e83-83cc-412ed0dcf69b)

In this example we use `8` for `button` and `12` for the outside border. If you add the distance from the inner element to the  border of the outside and add them together you get the correct border-radius. I havent though of this issue before and this is not the worst example. This will also cause "design" issues with our focus indicator. 

The best case would be to handle this with tokens in some way. That means we could replicate correctly in Figma, but i fear this might be to complex.

**Comment by unekinn** [comment]
> Tabs, there are no border around tabs. Where is this applied?
The radius is on the line under current tab and hovered tabs. As detailed in Slack this is incorrectly implemented currently, because of a typo(?), so there is currently no rounding in the React component.

> Tooltip can be circular. `full`

Like this?
<img width="156" alt="image" src="https://github.com/user-attachments/assets/bf7f5346-29b3-4fa3-9d55-6345526876be">

> Toggle group, Ill write more about this further down 👇 But I think toggle group can be full

Since your example is using the button (which has `default` radius) as reference, I assume it should be `border-radius.default + spacing.1` and not `full`?

**Comment by unekinn** [comment]
Someone also needs to decide what tokens to use for these values in storefront, as they don't exist after these border-radius changes

![Image](https://github.com/user-attachments/assets/e930cc8e-e49c-4f29-85f7-73674cdfc44b)

**Comment by Febakke** [comment]
> > Tabs, there are no border around tabs. Where is this applied?
> 
> The radius is on the line under current tab and hovered tabs. As detailed in Slack this is incorrectly implemented currently, because of a typo(?), so there is currently no rounding in the React component.
> 
> > Tooltip can be circular. `full`
> 
> Like this? <img alt="image" width="156" src="https://private-user-images.githubusercontent.com/910569/377100978-bf7f5346-29b3-4fa3-9d55-6345526876be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0OTcyODEsIm5iZiI6MTcyOTQ5Njk4MSwicGF0aCI6Ii85MTA1NjkvMzc3MTAwOTc4LWJmN2Y1MzQ2LTI5YjMtNGZhMy05ZDU1LTYzNDU1MjY4NzZiZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQwNzQ5NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNDM0N2Y4NTYwZDAwZmFhYTJkNzEyM2Y2YjI5YjdhOWVjNDE2OGJmMjkyYmIyZGQwZDk0MzUwNjI5ODA1ZDBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4ja4feSF1Jj6BGfhSuPB-hLrcWpN8Pdr97aPjAQE6rQ">
> 
> > Toggle group, Ill write more about this further down 👇 But I think toggle group can be full
> 
> Since your example is using the button (which has `default` radius) as reference, I assume it should be `border-radius.default + spacing.1` and not `full`?

I think tooltip can be full yes, are there any issues with doing this? 

**Togglegroup**
We might have an issue here, I see three ways the border-radius can go
1. border-radius.default + spacing.1 In most cases this will be correct
2. `border-radius.default=0` now we have an issue. If border radius is set to 0 on button then it should be 0 on the whole togglegroup
3. `border-radius.default=9999` Is there a problem with border-radius being set to 10 003? 😄

**Comment by Febakke** [comment]
> Someone also needs to decide what tokens to use for these values in storefront, as they don't exist after these border-radius changes
> 
> ![Image](https://github.com/user-attachments/assets/e930cc8e-e49c-4f29-85f7-73674cdfc44b)

Im not sure what elements they are referencing, but I would guess that they should be set to `large`
