### ISSUE TITLE
No need for forwardRef with React 19

### ISSUE THREAD

**Issue by vaarvik** [digdir/designsystemet#2579]
### Description

With React 19 `forwardRef` can be replaced by a simple `ref`: https://react.dev/blog/2024/04/25/react-19#ref-as-a-prop

**Comment by Barsnes** [comment]
Hi, thanks for the issue!
We still need to be backwards compatible with react 18, which we are also still on.
React 19 is still not released, and we would need to update to be able to use it, which is still a bit further down the road for us at the moment.

Due to the need to support backwards compatibility, we might need to keep using `forwardRef` for the forseeable future. It won't be removed in react 19, so it is fine to keep it as is for now,
