### ISSUE TITLE
Select: readOnly state

### ISSUE THREAD

**Issue by bjosttveit** [digdir/designsystemet#725]
### Description

Currently we are using `disabled` in app-frontend when a dropdown or multiple select has `readOnly: true`, but it was brought to our attention that the `disabled` state is very difficult to read. It would be great to have a proper `readOnly` state for the `Select` component similar to the `readOnly` state for the `TextField` component.

Example of an app using readOnly for dropdown:
![image](https://github.com/digdir/designsystem/assets/47412359/43c7b0c2-a386-48e6-a403-c7371fda6edc)

**Comment by SimenRokaas** [comment]
As the "bringer of attention", I would like to add that the deactivated dropdown was quite readable when I created the form - otherwise I would have created an issue then. It only became unreadable with frontend version 3.62. I think [this issue](https://github.com/Altinn/app-frontend-react/pull/1072) is the cause, which is why @bjosttveit referred this issue to the designsystem team.

**Comment by Febakke** [comment]
I have made a suggestion based on the new read-only design we have used for radios and checkboxes. Putting this in our backlog 👍

![Image](https://github.com/digdir/designsystem/assets/33222679/c35fdbf7-4293-4067-94e9-5372fc85a957)

**Comment by hflateland** [comment]
This is a important issue for org/srf.

**Comment by Barsnes** [comment]
Is this still relevant? The new [combobox](https://storybook.designsystemet.no/?path=/docs/felles-combobox--docs) has support for `readOnly`

**Comment by bjosttveit** [comment]
Looking good, we will migrate over to the new Combobox component 👍
